<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>

<!DOCTYPE html>
<html>
<head>
	<base href="<%=basePath%>">
	<title>DataGobble Analysis System</title>
	<link href="<%=request.getContextPath()%>/css/index.css" rel="stylesheet" type="text/css" />
	<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery-1.8.2.min.js"></script>
	<script type="text/javascript" src="<%=request.getContextPath()%>/js/index.js"></script>
</head>

<body>
	<section id="page-wrapper">
		
		<header>
		<h1>
		<img id="data-gobble-logo-img" alt="logo" src="<%=request.getContextPath()%>/images/data-gobble-logo.png">
		DataGobble Analysis System
		</h1>
		</header>
		
		<section>
			<h2>How to use this tool?</h2>
			<p>
				1. Select a text file with a series of values, one value per line. <br>
				2. Set the number of values you want to generate. <br>
				3. Submit the form to get the results.
			</p>
			<h2>Case Study</h2>
			<p>
				Test data: <a href="<%=request.getContextPath()%>/download/test-data/testdata-value-server.txt" target="_blank">Download Test Data</a>
				<br><br>
				This tool estimates a probability density function based on data from the file, 
				and then generate a sequence of numbers based on that density function <br>
				<br>
				The test file above is generated by the random number generation tool 
				with distribution type being exponential distribution, 
				the mean value being 10. We upload this file, set the number of samples to 100, 
				and get: <br>
				<br>
				14.787741438947267<br>
				16.189283369362744<br>
				2.6635799060923526<br>
				2.2562685415244625<br>
				17.01366288925154<br>
				14.787741438947267<br>
				0.7841379780719615<br>
				21.27418930232954<br>
				23.7495531436509<br>
				0.17394859465544835<br>
				...(other samples are omitted)<br>
				<br>
				Which looks like a exponential distribution with mean value 10. 
			</p>
			<h2>Example</h2>
			<p>
				Say we want to train a system simulation model with a series of data. 
				We get some data from real environment, but since it is quite expensive to do so, 
				the amount of data we get is quite limited. 
				For the training result be more accurate, we want to feed more data to the simulation model. 
				Now suppose we know that the input follows a certain distribution, 
				and we want to use this tool to generate more data. 
				To do so, we write the collected data to a file, one number per line and upload the file, 
				then we can get the results.
			</p>
			<h2>Demo Video</h2>
			<a href="http://youtu.be/33UCu-BiL-w" target="_blank">View demo</a>
		</section>
		
		<section class="form-section">
			<form action="valueServer" method="post" enctype="multipart/form-data">
				<fieldset>
					<legend>Value Server</legend>
					<input type="hidden" name="inputType" value="FILE">
					<label>Input File:</label>
					<input type="file" name="file"><br>
					<label>Number of samples:</label>
					<input type="text" name="numSample" value="500" ><br>
					<input type="submit" value="upload">
				</fieldset>
			</form>
		</section>
		
	</section>
</body>
</html>
